// All user-facing strings, en + fr. Plain object lookup — no i18n
// library. Placeholders use {name} and are substituted by t(key, vars).

export const strings = {
  en: {
    // Session screen
    appTitle: '⚓ Anchor Alarm',
    startMonitoring: '⚓ Start monitoring',
    startMonitoringNote: 'This phone stays on the boat',
    createSession: 'Create a session',
    creating: 'Creating…',
    watchRemotely: '👀 Watch remotely',
    watchRemotelyNote: 'Join a session running on the boat',
    sessionIdPlaceholder: 'Session ID',
    join: 'Join',
    scanQr: 'Scan QR',
    invalidSessionId: 'Please enter a valid session ID',
    sessionCreated: 'Session created',
    copied: 'Copied',
    shareHint: 'Scan from another phone to watch remotely — or share the ID.',
    openMap: 'Open the map',
    scanHint: 'Point the camera at the session QR code',
    cancel: 'Cancel',

    // Top strip / instrument panel
    back: 'Back',
    distanceToAnchor: 'Distance to anchor',
    zoneLabel: 'Zone',
    gpsLabel: 'GPS',
    waitingGps: 'Waiting for GPS signal…',
    waitingBoat: 'Waiting for boat position…',
    updatedAt: 'Updated {time}',

    // Anchor flow
    dropAnchor: '⚓ Drop anchor',
    armAlarm: 'Arm alarm',
    radiusHint: 'Slide, or drag the green handle on the map',
    adjustZone: 'Adjust zone',
    raiseAnchor: 'Raise anchor',
    raiseAnchorTitle: 'Raise anchor?',
    raiseAnchorMessage: 'This clears the anchor position and disarms the alarm.',
    keepWatching: 'Keep watching',

    // Leave-session dialog
    leaveTitle: 'Leave the session?',
    leaveMessage: 'If you leave now, the anchor position and zone will be lost.',
    leave: 'Leave',
    stay: 'Stay',

    // Map popups
    boatPosition: '📍 Boat position',
    accuracyMeters: 'Accuracy: {n} m',
    anchorPosition: '⚓ Anchor position',
    adjustRadius: 'Adjust radius',
    removeAnchor: 'Remove anchor',

    // Status pill + sheet
    pillNoGps: 'No GPS',
    pillGpsWeak: 'GPS weak',
    pillOfflineLocal: 'Offline — local only',
    pillOffline: 'Offline',
    pillNoData: 'No data',
    pillDataStale: 'Data stale',
    pillMonitoring: 'Monitoring',
    pillWatching: 'Watching',
    pillNotArmed: 'Not armed',
    sheetBoatData: 'Boat data',
    sheetServer: 'Server',
    sheetConnected: 'Connected',
    sheetDisconnected: 'Disconnected',
    sheetArmed: 'Armed',
    sheetNotArmed: 'Not armed',
    sheetFixAgo: 'Fix {s}s ago',
    sheetNoFix: 'No fix yet',
    sheetError: 'Error: {msg}',
    close: 'Close',

    // Alarm screen
    anchorDragging: 'ANCHOR DRAGGING',
    triggeredInfo: 'Triggered {time} · outside zone for {s}s',
    zoneIs: 'zone is {n} m',
    drifting: 'drifting {dir} at {kn} kn',
    slideToSilence: 'Slide to silence',
    rearmCaption: 'Alarm re-arms when the boat returns inside the zone',

    // Native notifications (alarm + foreground service)
    notifTitle: '🚨 ANCHOR ALARM',
    notifBody: 'Your boat has left the anchor zone! {loc}',
    unknownLocation: 'Unknown location',
    fgsTitle: 'Anchor alarm active',
    fgsMessage: 'Tracking the boat position',

    // Errors
    errConnecting: 'Connecting to server, please wait…',
    errCreateSession: 'Failed to create session: {msg}',
    errConnection: 'Connection error: {msg}',
    errLocPermission: 'Location permission was not granted',
    errDropAnchor: 'Could not set the anchor position: {msg}',

    // Leaflet-draw toolbar
    drawZone: 'Draw an anchor zone',
    drawCancel: 'Cancel',
    drawFinish: 'Finish',
    drawDeleteLast: 'Delete last point',
    drawTooltipStart: 'Tap to start drawing the zone',
    drawTooltipCont: 'Tap to continue drawing the zone',
    drawTooltipEnd: 'Tap the first point to close the zone',
    editZone: 'Edit the zone',
    editZoneNone: 'No zone to edit',
    deleteZone: 'Delete the zone',
    deleteZoneNone: 'No zone to delete',
    editSave: 'Save',
    editCancel: 'Cancel',
    editTooltip: 'Drag the points to reshape the zone',
    deleteTooltip: 'Tap a zone to delete it'
  },

  fr: {
    appTitle: '⚓ Alarme de Mouillage',
    startMonitoring: '⚓ Surveiller ce bateau',
    startMonitoringNote: 'Ce téléphone reste à bord',
    createSession: 'Créer une session',
    creating: 'Création…',
    watchRemotely: '👀 Suivre à distance',
    watchRemotelyNote: 'Rejoindre une session en cours sur le bateau',
    sessionIdPlaceholder: 'ID de session',
    join: 'Rejoindre',
    scanQr: 'Scanner le QR',
    invalidSessionId: 'Veuillez entrer un ID de session valide',
    sessionCreated: 'Session créée',
    copied: 'Copié',
    shareHint: "Scannez depuis un autre téléphone pour suivre à distance — ou partagez l'ID.",
    openMap: 'Ouvrir la carte',
    scanHint: 'Visez le QR code de la session',
    cancel: 'Annuler',

    back: 'Retour',
    distanceToAnchor: "Distance à l'ancre",
    zoneLabel: 'Zone',
    gpsLabel: 'GPS',
    waitingGps: 'En attente du signal GPS…',
    waitingBoat: 'En attente de la position du bateau…',
    updatedAt: 'Mis à jour {time}',

    dropAnchor: "⚓ Mouiller l'ancre",
    armAlarm: "Armer l'alarme",
    radiusHint: 'Glissez le curseur, ou le point vert sur la carte',
    adjustZone: 'Ajuster la zone',
    raiseAnchor: "Lever l'ancre",
    raiseAnchorTitle: "Lever l'ancre ?",
    raiseAnchorMessage: "La position de l'ancre sera effacée et l'alarme désarmée.",
    keepWatching: 'Continuer la surveillance',

    leaveTitle: 'Quitter la session ?',
    leaveMessage: "Si vous quittez maintenant, la position de l'ancre et la zone seront perdues.",
    leave: 'Quitter',
    stay: 'Rester',

    boatPosition: '📍 Position du bateau',
    accuracyMeters: 'Précision : {n} m',
    anchorPosition: "⚓ Position de l'ancre",
    adjustRadius: 'Ajuster le rayon',
    removeAnchor: "Retirer l'ancre",

    pillNoGps: 'Pas de GPS',
    pillGpsWeak: 'GPS faible',
    pillOfflineLocal: 'Hors ligne — local seul',
    pillOffline: 'Hors ligne',
    pillNoData: 'Pas de données',
    pillDataStale: 'Données anciennes',
    pillMonitoring: 'Surveillance',
    pillWatching: 'Suivi',
    pillNotArmed: 'Non armée',
    sheetBoatData: 'Données bateau',
    sheetServer: 'Serveur',
    sheetConnected: 'Connecté',
    sheetDisconnected: 'Déconnecté',
    sheetArmed: 'Armée',
    sheetNotArmed: 'Non armée',
    sheetFixAgo: 'Fix il y a {s}s',
    sheetNoFix: 'Aucun fix',
    sheetError: 'Erreur : {msg}',
    close: 'Fermer',

    anchorDragging: "L'ANCRE DÉRAPE",
    triggeredInfo: 'Déclenchée à {time} · hors zone depuis {s}s',
    zoneIs: 'zone de {n} m',
    drifting: 'dérive {dir} à {kn} nd',
    slideToSilence: 'Glisser pour acquitter',
    rearmCaption: "L'alarme se réarme quand le bateau revient dans la zone",

    notifTitle: '🚨 ALARME MOUILLAGE',
    notifBody: 'Votre bateau a quitté la zone de mouillage ! {loc}',
    unknownLocation: 'Position inconnue',
    fgsTitle: 'Alarme de mouillage active',
    fgsMessage: 'Surveillance de la position du bateau',

    errConnecting: 'Connexion au serveur, patientez…',
    errCreateSession: 'Échec de création de session : {msg}',
    errConnection: 'Erreur de connexion : {msg}',
    errLocPermission: 'Permission de localisation refusée',
    errDropAnchor: "Impossible de définir la position de l'ancre : {msg}",

    drawZone: 'Dessiner une zone de mouillage',
    drawCancel: 'Annuler',
    drawFinish: 'Terminer',
    drawDeleteLast: 'Supprimer le dernier point',
    drawTooltipStart: 'Touchez pour commencer la zone',
    drawTooltipCont: 'Touchez pour continuer la zone',
    drawTooltipEnd: 'Touchez le premier point pour fermer la zone',
    editZone: 'Modifier la zone',
    editZoneNone: 'Aucune zone à modifier',
    deleteZone: 'Supprimer la zone',
    deleteZoneNone: 'Aucune zone à supprimer',
    editSave: 'Enregistrer',
    editCancel: 'Annuler',
    editTooltip: 'Faites glisser les points pour modifier la zone',
    deleteTooltip: 'Touchez une zone pour la supprimer'
  }
};
